# SQLite version 3.x
#   gem install sqlite3

#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000
  
  
 development:
  adapter: postgresql
  encoding: unicode
  database: cg_development
  pool: 5
  username: postgres
  password: salesforce1
  host: localhost
  
 test:
  adapter: postgresql
  encoding: unicode
  database: cg_test
  pool: 5
  username: postgres
  password: salesforce1
  host: localhost
